# Generated by Django 5.2 on 2025-04-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('personal', 'Personal'), ('work', 'Work'), ('study', 'Study'), ('other', 'Other')], default='personal', max_length=20)),
            ],
        ),
    ]
